application: dumbboard-pythonvlc
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: templates/css

- url: /js
  static_dir: templates/js

- url: /fonts
  static_dir: templates/fonts

- url: /backburner/.*
  script: backburner.app
  login: admin


- url: /test.*
  script: main.app
  login: admin

- url: .*
  script: main.app

